"""empty message

Revision ID: 7a48bf052a07
Revises: 1a37b766fd94
Create Date: 2024-02-11 20:58:36.386878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a48bf052a07'
down_revision = '1a37b766fd94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_pages', schema=None) as batch_op:
        batch_op.alter_column('first_para',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10000),
               existing_nullable=False)
        batch_op.alter_column('second_para',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=10000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about_pages', schema=None) as batch_op:
        batch_op.alter_column('second_para',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('first_para',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
